# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/baby_ray.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/baby_ray.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/baby_ray.proto\x12\x07\x62\x61\x62yray\"\x81\x01\n\x0fRegisterRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x11\n\tworker_ip\x18\x02 \x01(\t\x12\x13\n\x0bworker_port\x18\x03 \x01(\x05\x12\x17\n\x0ftotal_cpu_cores\x18\x04 \x01(\x01\x12\x1a\n\x12total_memory_bytes\x18\x05 \x01(\x03\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"n\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x19\n\x11\x63pu_usage_percent\x18\x02 \x01(\x01\x12\x19\n\x11memory_used_bytes\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\":\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"\xd4\x01\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x17\n\x0fsequence_length\x18\x03 \x01(\x05\x12\x12\n\nhidden_dim\x18\x04 \x01(\x05\x12\x0e\n\x06\x65pochs\x18\x05 \x01(\x05\x12\x15\n\rlearning_rate\x18\x06 \x01(\x01\x12\x14\n\x0cthread_limit\x18\x07 \x01(\x05\x12\x18\n\x10gpu_scale_factor\x18\x08 \x01(\x01\x12\x1d\n\x15\x64\x65pendency_object_ids\x18\t \x03(\t\"6\n\x0cTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"$\n\x11TaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"U\n\x12TaskStatusResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x01\x12\x0c\n\x04loss\x18\x04 \x01(\x02\x32\xa4\x02\n\x0e\x42\x61\x62yRayService\x12\x45\n\x0eRegisterWorker\x12\x18.babyray.RegisterRequest\x1a\x19.babyray.RegisterResponse\x12\x46\n\rSendHeartbeat\x12\x19.babyray.HeartbeatRequest\x1a\x1a.babyray.HeartbeatResponse\x12\x39\n\nAssignTask\x12\x14.babyray.TaskRequest\x1a\x15.babyray.TaskResponse\x12H\n\rGetTaskStatus\x12\x1a.babyray.TaskStatusRequest\x1a\x1b.babyray.TaskStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.baby_ray_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=34
  _globals['_REGISTERREQUEST']._serialized_end=163
  _globals['_REGISTERRESPONSE']._serialized_start=165
  _globals['_REGISTERRESPONSE']._serialized_end=217
  _globals['_HEARTBEATREQUEST']._serialized_start=219
  _globals['_HEARTBEATREQUEST']._serialized_end=329
  _globals['_HEARTBEATRESPONSE']._serialized_start=331
  _globals['_HEARTBEATRESPONSE']._serialized_end=389
  _globals['_TASKREQUEST']._serialized_start=392
  _globals['_TASKREQUEST']._serialized_end=604
  _globals['_TASKRESPONSE']._serialized_start=606
  _globals['_TASKRESPONSE']._serialized_end=660
  _globals['_TASKSTATUSREQUEST']._serialized_start=662
  _globals['_TASKSTATUSREQUEST']._serialized_end=698
  _globals['_TASKSTATUSRESPONSE']._serialized_start=700
  _globals['_TASKSTATUSRESPONSE']._serialized_end=785
  _globals['_BABYRAYSERVICE']._serialized_start=788
  _globals['_BABYRAYSERVICE']._serialized_end=1080
# @@protoc_insertion_point(module_scope)
