# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import babyray_pb2 as proto_dot_babyray__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/babyray_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BabyRayServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/babyray.BabyRayService/RegisterWorker',
                request_serializer=proto_dot_babyray__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_babyray__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.DeregisterWorker = channel.unary_unary(
                '/babyray.BabyRayService/DeregisterWorker',
                request_serializer=proto_dot_babyray__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=proto_dot_babyray__pb2.DeregisterResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/babyray.BabyRayService/SendHeartbeat',
                request_serializer=proto_dot_babyray__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_babyray__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.AssignTask = channel.unary_unary(
                '/babyray.BabyRayService/AssignTask',
                request_serializer=proto_dot_babyray__pb2.TaskAssignment.SerializeToString,
                response_deserializer=proto_dot_babyray__pb2.TaskResult.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/babyray.BabyRayService/GetTaskStatus',
                request_serializer=proto_dot_babyray__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=proto_dot_babyray__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.ResizeResources = channel.unary_unary(
                '/babyray.BabyRayService/ResizeResources',
                request_serializer=proto_dot_babyray__pb2.ResizeRequest.SerializeToString,
                response_deserializer=proto_dot_babyray__pb2.ResizeResponse.FromString,
                _registered_method=True)


class BabyRayServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Worker -> Head: Worker 등록 및 제거
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Worker -> Head: 주기적 생존 신고 및 자원 상태 전송
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTask(self, request, context):
        """Head -> Worker: 작업 할당 및 상태 모니터링
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizeResources(self, request, context):
        """Head -> Worker: cGroup 자원 격리 제한 동적 변경
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BabyRayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=proto_dot_babyray__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_babyray__pb2.RegisterResponse.SerializeToString,
            ),
            'DeregisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterWorker,
                    request_deserializer=proto_dot_babyray__pb2.DeregisterRequest.FromString,
                    response_serializer=proto_dot_babyray__pb2.DeregisterResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=proto_dot_babyray__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_babyray__pb2.HeartbeatResponse.SerializeToString,
            ),
            'AssignTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTask,
                    request_deserializer=proto_dot_babyray__pb2.TaskAssignment.FromString,
                    response_serializer=proto_dot_babyray__pb2.TaskResult.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=proto_dot_babyray__pb2.TaskStatusRequest.FromString,
                    response_serializer=proto_dot_babyray__pb2.TaskStatusResponse.SerializeToString,
            ),
            'ResizeResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ResizeResources,
                    request_deserializer=proto_dot_babyray__pb2.ResizeRequest.FromString,
                    response_serializer=proto_dot_babyray__pb2.ResizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'babyray.BabyRayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('babyray.BabyRayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BabyRayService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/RegisterWorker',
            proto_dot_babyray__pb2.RegisterRequest.SerializeToString,
            proto_dot_babyray__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/DeregisterWorker',
            proto_dot_babyray__pb2.DeregisterRequest.SerializeToString,
            proto_dot_babyray__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/SendHeartbeat',
            proto_dot_babyray__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_babyray__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/AssignTask',
            proto_dot_babyray__pb2.TaskAssignment.SerializeToString,
            proto_dot_babyray__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/GetTaskStatus',
            proto_dot_babyray__pb2.TaskStatusRequest.SerializeToString,
            proto_dot_babyray__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResizeResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/ResizeResources',
            proto_dot_babyray__pb2.ResizeRequest.SerializeToString,
            proto_dot_babyray__pb2.ResizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
