# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import baby_ray_pb2 as proto_dot_baby__ray__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/baby_ray_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BabyRayServiceStub:
    """Baby Ray 분산 시스템 핵심 서비스 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/babyray.BabyRayService/RegisterWorker',
                request_serializer=proto_dot_baby__ray__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_baby__ray__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/babyray.BabyRayService/SendHeartbeat',
                request_serializer=proto_dot_baby__ray__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_baby__ray__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.AssignTask = channel.unary_unary(
                '/babyray.BabyRayService/AssignTask',
                request_serializer=proto_dot_baby__ray__pb2.TaskRequest.SerializeToString,
                response_deserializer=proto_dot_baby__ray__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/babyray.BabyRayService/GetTaskStatus',
                request_serializer=proto_dot_baby__ray__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=proto_dot_baby__ray__pb2.TaskStatusResponse.FromString,
                _registered_method=True)


class BabyRayServiceServicer:
    """Baby Ray 분산 시스템 핵심 서비스 정의
    """

    def RegisterWorker(self, request, context):
        """1. Worker -> Head: Worker 기동 시 최초 등록 요청
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """2. Worker -> Head: 생존 신호 및 실시간 CPU/Memory 메트릭 전송 (Heartbeat)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTask(self, request, context):
        """3. Head -> Worker: AI 학습 태스크 배정 요청
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """4. Head -> Worker: 실행 중인 태스크 상태 확인 (Polling)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BabyRayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=proto_dot_baby__ray__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_baby__ray__pb2.RegisterResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=proto_dot_baby__ray__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_baby__ray__pb2.HeartbeatResponse.SerializeToString,
            ),
            'AssignTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTask,
                    request_deserializer=proto_dot_baby__ray__pb2.TaskRequest.FromString,
                    response_serializer=proto_dot_baby__ray__pb2.TaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=proto_dot_baby__ray__pb2.TaskStatusRequest.FromString,
                    response_serializer=proto_dot_baby__ray__pb2.TaskStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'babyray.BabyRayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('babyray.BabyRayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BabyRayService:
    """Baby Ray 분산 시스템 핵심 서비스 정의
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/RegisterWorker',
            proto_dot_baby__ray__pb2.RegisterRequest.SerializeToString,
            proto_dot_baby__ray__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/SendHeartbeat',
            proto_dot_baby__ray__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_baby__ray__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/AssignTask',
            proto_dot_baby__ray__pb2.TaskRequest.SerializeToString,
            proto_dot_baby__ray__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/babyray.BabyRayService/GetTaskStatus',
            proto_dot_baby__ray__pb2.TaskStatusRequest.SerializeToString,
            proto_dot_baby__ray__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
